backend:
  name: git-gateway
  branch: decap-testing # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "assets/images" # Media files will be stored in the repo under images/uploads
public_folder: "/assets/images"
collections:
  - name: "shows" # Used in routes, e.g., /admin/collections/blog
    label: "Shows" # Used in the UI
    folder: "_shows/"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "show-info"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Querter"
        name: "quarter"
        hint: "Quarter that a show performs in"
        widget: "select"
        options: ["fall", "winter", "spring"]
# TODO add more collections here